name: renewify_login
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_auth: ^5.1.2
  firebase_database: ^11.2.0
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  http: ^1.2.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  geolocator: ^13.0.2
  flutter_map: ^7.0.2
  image_picker: ^1.1.2
  location: ^7.0.1
  provider: ^6.1.2
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  cloud_firestore: ^5.6.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
