name: renewify_login
description: "A new Flutter project."
<<<<<<< HEAD
publish_to: 'none'
=======
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
>>>>>>> 2894a4c3b299db4a521ce84532adef8da767119f

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
=======
  intl: ^0.19.0
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.2.0
>>>>>>> 2894a4c3b299db4a521ce84532adef8da767119f
  firebase_auth: ^5.1.2
  firebase_database: ^11.2.0
  font_awesome_flutter: ^10.8.0
  http: ^1.2.2
  flutter_localizations:
    sdk: flutter
  geolocator: ^13.0.2
  flutter_map: ^7.0.2
  image_picker: ^1.1.2
  location: ^7.0.1
  provider: ^6.1.2
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
<<<<<<< HEAD
  cloud_firestore: ^5.6.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
=======

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
>>>>>>> 2894a4c3b299db4a521ce84532adef8da767119f

flutter:
  uses-material-design: true
  assets:
    - assets/images/
<<<<<<< HEAD
=======
 
>>>>>>> 2894a4c3b299db4a521ce84532adef8da767119f
